In [3]:
!pip install fingertips_py

Requirement already satisfied: fingertips_py in c:\users\heathermoorhouse\appdata\local\programs\python\python314\lib\site-packages (0.4.2)
Requirement already satisfied: pandas>=1.5 in c:\users\heathermoorhouse\appdata\local\programs\python\python314\lib\site-packages (from fingertips_py) (2.3.3)
Requirement already satisfied: requests in c:\users\heathermoorhouse\appdata\local\programs\python\python314\lib\site-packages (from fingertips_py) (2.32.5)
Requirement already satisfied: numpy>=1.26.0 in c:\users\heathermoorhouse\appdata\local\programs\python\python314\lib\site-packages (from pandas>=1.5->fingertips_py) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\heathermoorhouse\appdata\local\programs\python\python314\lib\site-packages (from pandas>=1.5->fingertips_py) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\heathermoorhouse\appdata\local\programs\python\python314\lib\site-packages (from pandas>=1.5->fingertips_py) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\heathermoorhouse\appdata\local\programs\python\python314\lib\site-packages (from pandas>=1.5->fingertips_py) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\heathermoorhouse\appdata\local\programs\python\python314\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.5->fingertips_py) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\heathermoorhouse\appdata\local\programs\python\python314\lib\site-packages (from requests->fingertips_py) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\heathermoorhouse\appdata\local\programs\python\python314\lib\site-packages (from requests->fingertips_py) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\heathermoorhouse\appdata\local\programs\python\python314\lib\site-packages (from requests->fingertips_py) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\heathermoorhouse\appdata\local\programs\python\python314\lib\site-packages (from requests->fingertips_py) (2025.10.5)

In [1]:
#Import Relevant Libraries
# HTTP requests to call the API
import requests

# Data handling
import pandas as pd

# Plotting
import matplotlib.pyplot as plt

In [4]:
# Fingertips API wrapper
import fingertips_py as ftp

In [ ]:
#Confirm API Connection

First explored the Fingertips API to identify available data profiles and understand how indicators are organised. Profiles group related public health metrics for easier discovery

In [5]:
dir(ftp)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 'api_calls',
 'area_data',
 'deprivation_decile',
 'get_age_from_id',
 'get_age_id',
 'get_all_ages',
 'get_all_areas',
 'get_all_areas_for_all_indicators',
 'get_all_data_for_indicators',
 'get_all_data_for_profile',
 'get_all_profiles',
 'get_all_sexes',
 'get_all_value_notes',
 'get_area_type_ids_for_profile',
 'get_area_types_as_dict',
 'get_area_types_for_profile',
 'get_areas_for_area_type',
 'get_data_by_indicator_ids',
 'get_data_for_indicator_at_all_available_geographies',
 'get_domains_in_profile',
 'get_json',
 'get_metadata',
 'get_metadata_for_all_indicators',
 'get_metadata_for_all_indicators_from_csv',
 'get_metadata_for_domain_as_dataframe',
 'get_metadata_for_indicator',
 'get_metadata_for_indicator_as_dataframe',
 'get_metadata_for_profile_as_dataframe',
 'get_multiplier_and_calculation_for_indicator',
 'get_profile_by_id',
 'get_profile_by_name',
 'get_sex_from_id',
 'get_sex_id',
 'get_value_note_id',
 'make_request',
 'metadata',
 'retrieve_data']

In [6]:
available_profiles = ftp.get_all_profiles()

In [7]:
# Check what type it is
type(available_profiles)

dict

In [8]:
# Print the profile dictionary
available_profiles

{18: {'Id': 18,
  'Name': 'Smoking Profile',
  'Key': 'tobacco-control',
  'GroupIds': [1938132885,
   1938132886,
   1938132900,
   1938132887,
   1938132888,
   1938132889,
   1938132890],
  'GroupMetadata': [{'Id': 1938132885,
    'Name': 'Key indicators',
    'Sequence': 1,
    'ProfileId': 18,
    'DataAvailable': [{'AreaTypeId': 6, 'IndicatorCount': 22},
     {'AreaTypeId': 15, 'IndicatorCount': 20},
     {'AreaTypeId': 66, 'IndicatorCount': 2},
     {'AreaTypeId': 221, 'IndicatorCount': 10},
     {'AreaTypeId': 401, 'IndicatorCount': 18},
     {'AreaTypeId': 402, 'IndicatorCount': 18},
     {'AreaTypeId': 501, 'IndicatorCount': 18},
     {'AreaTypeId': 502, 'IndicatorCount': 18},
     {'AreaTypeId': 15, 'IndicatorCount': 10}]},
   {'Id': 1938132886,
    'Name': 'Smoking prevalence in adults',
    'Sequence': 2,
    'ProfileId': 18,
    'DataAvailable': [{'AreaTypeId': 6, 'IndicatorCount': 26},
     {'AreaTypeId': 15, 'IndicatorCount': 26},
     {'AreaTypeId': 66, 'IndicatorCount': 20},
     {'AreaTypeId': 221, 'IndicatorCount': 14},
     {'AreaTypeId': 223, 'IndicatorCount': 6},
     {'AreaTypeId': 401, 'IndicatorCount': 26},
     {'AreaTypeId': 402, 'IndicatorCount': 26},
     {'AreaTypeId': 501, 'IndicatorCount': 26},
     {'AreaTypeId': 502, 'IndicatorCount': 26},
     {'AreaTypeId': 15, 'IndicatorCount': 10}]},
   {'Id': 1938132900,
    'Name': 'Smoking prevalence in priority populations',
    'Sequence': 3,
    'ProfileId': 18,
    'DataAvailable': [{'AreaTypeId': 6, 'IndicatorCount': 40},
     {'AreaTypeId': 15, 'IndicatorCount': 40},
     {'AreaTypeId': 66, 'IndicatorCount': 4},
     {'AreaTypeId': 221, 'IndicatorCount': 6},
     {'AreaTypeId': 401, 'IndicatorCount': 20},
     {'AreaTypeId': 402, 'IndicatorCount': 32},
     {'AreaTypeId': 501, 'IndicatorCount': 20},
     {'AreaTypeId': 502, 'IndicatorCount': 32},
     {'AreaTypeId': 15, 'IndicatorCount': 18}]},
   {'Id': 1938132887,
    'Name': 'Smoking related mortality',
    'Sequence': 4,
    'ProfileId': 18,
    'DataAvailable': [{'AreaTypeId': 6, 'IndicatorCount': 24},
     {'AreaTypeId': 15, 'IndicatorCount': 24},
     {'AreaTypeId': 401, 'IndicatorCount': 6},
     {'AreaTypeId': 402, 'IndicatorCount': 20},
     {'AreaTypeId': 501, 'IndicatorCount': 6},
     {'AreaTypeId': 502, 'IndicatorCount': 20},
     {'AreaTypeId': 15, 'IndicatorCount': 10}]},
   {'Id': 1938132888,
    'Name': 'Smoking related ill health',
    'Sequence': 5,
    'ProfileId': 18,
    'DataAvailable': [{'AreaTypeId': 6, 'IndicatorCount': 18},
     {'AreaTypeId': 15, 'IndicatorCount': 18},
     {'AreaTypeId': 66, 'IndicatorCount': 2},
     {'AreaTypeId': 221, 'IndicatorCount': 2},
     {'AreaTypeId': 223, 'IndicatorCount': 2},
     {'AreaTypeId': 401, 'IndicatorCount': 12},
     {'AreaTypeId': 402, 'IndicatorCount': 16},
     {'AreaTypeId': 501, 'IndicatorCount': 12},
     {'AreaTypeId': 502, 'IndicatorCount': 16},
     {'AreaTypeId': 15, 'IndicatorCount': 9}]},
   {'Id': 1938132889,
    'Name': 'Impact of smoking',
    'Sequence': 6,
    'ProfileId': 18,
    'DataAvailable': []},
   {'Id': 1938132890,
    'Name': 'Smoking quitters',
    'Sequence': 7,
    'ProfileId': 18,
    'DataAvailable': [{'AreaTypeId': 6, 'IndicatorCount': 14},
     {'AreaTypeId': 15, 'IndicatorCount': 14},
     {'AreaTypeId': 402, 'IndicatorCount': 14},
     {'AreaTypeId': 502, 'IndicatorCount': 14},
     {'AreaTypeId': 15, 'IndicatorCount': 7}]}],
  'Visualisations': ['Overview',
   'CompareAreas',
   'Trends',
   'Reports',
   'AreaProfile',
   'CompareIndicators',
   'Population',
   'Definitions',
   'Inequalities',
   'BoxPlots',
   'Map',
   'Download'],
  'HasRecentTrends': True,
  'StartValueAxisFromZero': False,
  'IsChangeFromPreviousPeriodShown': True,
  'DefaultAreaTypeId': 15,
  'DefaultTabId': 1,
  'IgnoredSpineChartAreas': ['E06000053', 'E09000001'],
  'OpenInequalitiesOnAreaData': False,
  'HasAnyData': True,
  'HasOwnFrontPage': True},
 19: {'Id': 19,
  'Name': 'Public Health Outcomes Framework',
  'Key': 'public-health-outcomes-framework',
  'GroupIds': [1000049, 1000041, 1000042, 1000043, 1000044, 1938132983],
  'GroupMetadata': [{'Id': 1000049,
    'Name': 'A. Overarching indicators',
    'Sequence': 1,
    'ProfileId': 19,
    'DataAvailable': [{'AreaTypeId': 6, 'IndicatorCount': 40},
     {'AreaTypeId': 15, 'IndicatorCount': 44},
     {'AreaTypeId': 221, 'IndicatorCount': 8},
     {'AreaTypeId': 223, 'IndicatorCount': 8},
     {'AreaTypeId': 301, 'IndicatorCount': 24},
     {'AreaTypeId': 302, 'IndicatorCount': 38},
     {'AreaTypeId': 501, 'IndicatorCount': 24},
     {'AreaTypeId': 502, 'IndicatorCount': 44},
     {'AreaTypeId': 15, 'IndicatorCount': 10}]},
   {'Id': 1000041,
    'Name': 'B. Wider determinants of health',
    'Sequence': 2,
    'ProfileId': 19,
    'DataAvailable': [{'AreaTypeId': 6, 'IndicatorCount': 72},
     {'AreaTypeId': 15, 'IndicatorCount': 72},
     {'AreaTypeId': 221, 'IndicatorCount': 32},
     {'AreaTypeId': 223, 'IndicatorCount': 32},
     {'AreaTypeId': 301, 'IndicatorCount': 36},
     {'AreaTypeId': 302, 'IndicatorCount': 72},
     {'AreaTypeId': 501, 'IndicatorCount': 36},
     {'AreaTypeId': 502, 'IndicatorCount': 72},
     {'AreaTypeId': 15, 'IndicatorCount': 36}]},
   {'Id': 1000042,
    'Name': 'C. Health improvement',
    'Sequence': 3,
    'ProfileId': 19,
    'DataAvailable': [{'AreaTypeId': 6, 'IndicatorCount': 130},
     {'AreaTypeId': 15, 'IndicatorCount': 130},
     {'AreaTypeId': 221, 'IndicatorCount': 62},
     {'AreaTypeId': 223, 'IndicatorCount': 50},
     {'AreaTypeId': 301, 'IndicatorCount': 72},
     {'AreaTypeId': 302, 'IndicatorCount': 110},
     {'AreaTypeId': 501, 'IndicatorCount': 72},
     {'AreaTypeId': 502, 'IndicatorCount': 110},
     {'AreaTypeId': 15, 'IndicatorCount': 63}]},
   {'Id': 1000043,
    'Name': 'D. Health protection',
    'Sequence': 4,
    'ProfileId': 19,
    'DataAvailable': [{'AreaTypeId': 6, 'IndicatorCount': 72},
     {'AreaTypeId': 15, 'IndicatorCount': 72},
     {'AreaTypeId': 221, 'IndicatorCount': 64},
     {'AreaTypeId': 223, 'IndicatorCount': 26},
     {'AreaTypeId': 301, 'IndicatorCount': 18},
     {'AreaTypeId': 302, 'IndicatorCount': 72},
     {'AreaTypeId': 501, 'IndicatorCount': 18},
     {'AreaTypeId': 502, 'IndicatorCount': 72},
     {'AreaTypeId': 15, 'IndicatorCount': 33}]},
   {'Id': 1000044,
    'Name': 'E. Healthcare and premature mortality',
    'Sequence': 5,
    'ProfileId': 19,
    'DataAvailable': [{'AreaTypeId': 6, 'IndicatorCount': 70},
     {'AreaTypeId': 15, 'IndicatorCount': 72},
     {'AreaTypeId': 221, 'IndicatorCount': 60},
     {'AreaTypeId': 223, 'IndicatorCount': 60},
     {'AreaTypeId': 301, 'IndicatorCount': 50},
     {'AreaTypeId': 302, 'IndicatorCount': 62},
     {'AreaTypeId': 501, 'IndicatorCount': 50},
     {'AreaTypeId': 502, 'IndicatorCount': 62},
     {'AreaTypeId': 15, 'IndicatorCount': 26}]},
   {'Id': 1938132983,
    'Name': 'Supporting information',
    'Sequence': 6,
    'ProfileId': 19,
    'DataAvailable': [{'AreaTypeId': 6, 'IndicatorCount': 10},
     {'AreaTypeId': 15, 'IndicatorCount': 10},
     {'AreaTypeId': 221, 'IndicatorCount': 6},
     {'AreaTypeId': 223, 'IndicatorCount': 6},
     {'AreaTypeId': 301, 'IndicatorCount': 10},
     {'AreaTypeId': 302, 'IndicatorCount': 10},
     {'AreaTypeId': 501, 'IndicatorCount': 10},
     {'AreaTypeId': 502, 'IndicatorCount': 10},
     {'AreaTypeId': 15, 'IndicatorCount': 5}]}],
  'Visualisations': ['Overview',
   'CompareAreas',
   'Trends',
   'Reports',
   'AreaProfile',
   'CompareIndicators',
   'Population',
   'Definitions',
   'Inequalities',
   'BoxPlots',
   'Map',
   'Download'],
  'HasRecentTrends': True,
  'StartValueAxisFromZero': True,
  'IsChangeFromPreviousPeriodShown': True,
  'DefaultAreaTypeId': 502,
  'DefaultTabId': 3,
  'IgnoredSpineChartAreas': ['E06000053', 'E09000001'],
  'OpenInequalitiesOnAreaData': False,
  'HasAnyData': True,
  'HasOwnFrontPage': True},
 20: {'Id': 20,
  'Name': 'National General Practice Profiles',
  'Key': 'general-practice',
  'GroupIds': [2000005,
   1938132829,
   3000008,
   3000007,
   3000009,
   3000010,
   2000002,
   1938133477,
   2000003,
   2000004,
   2000006,
   1938132970,
   1938133380],
  'GroupMetadata': [{'Id': 2000005,
    'Name': 'Practice summary',
    'Sequence': 1,
    'ProfileId': 20,
    'DataAvailable': [{'AreaTypeId': 7, 'IndicatorCount': 18},
     {'AreaTypeId': 15, 'IndicatorCount': 18},
     {'AreaTypeId': 66, 'IndicatorCount': 18},
     {'AreaTypeId': 204, 'IndicatorCount': 18},
     {'AreaTypeId': 221, 'IndicatorCount': 18},
     {'AreaTypeId': 15, 'IndicatorCount': 4}]},
   {'Id': 1938132829,
    'Name': 'Cancer',
    'Sequence': 2,
    'ProfileId': 20,
    'DataAvailable': [{'AreaTypeId': 7, 'IndicatorCount': 12},
     {'AreaTypeId': 15, 'IndicatorCount': 12},
     {'AreaTypeId': 66, 'IndicatorCount': 12},
     {'AreaTypeId': 204, 'IndicatorCount': 12},
     {'AreaTypeId': 221, 'IndicatorCount': 12},
     {'AreaTypeId': 15, 'IndicatorCount': 6}]},
   {'Id': 3000008,
    'Name': 'CVD - Coronary Heart Disease',
    'Sequence': 3,
    'ProfileId': 20,
    'DataAvailable': [{'AreaTypeId': 7, 'IndicatorCount': 10},
     {'AreaTypeId': 15, 'IndicatorCount': 10},
     {'AreaTypeId': 66, 'IndicatorCount': 10},
     {'AreaTypeId': 204, 'IndicatorCount': 10},
     {'AreaTypeId': 221, 'IndicatorCount': 10},
     {'AreaTypeId': 15, 'IndicatorCount': 5}]},
   {'Id': 3000007,
    'Name': 'CVD - Stroke and TIA',
    'Sequence': 4,
    'ProfileId': 20,
    'DataAvailable': [{'AreaTypeId': 7, 'IndicatorCount': 10},
     {'AreaTypeId': 15, 'IndicatorCount': 10},
     {'AreaTypeId': 66, 'IndicatorCount': 10},
     {'AreaTypeId': 204, 'IndicatorCount': 10},
     {'AreaTypeId': 221, 'IndicatorCount': 10},
     {'AreaTypeId': 15, 'IndicatorCount': 5}]},
   {'Id': 3000009,
    'Name': 'CVD - Heart Failure and Atrial Fibrillation',
    'Sequence': 5,
    'ProfileId': 20,
    'DataAvailable': [{'AreaTypeId': 7, 'IndicatorCount': 18},
     {'AreaTypeId': 15, 'IndicatorCount': 18},
     {'AreaTypeId': 66, 'IndicatorCount': 18},
     {'AreaTypeId': 204, 'IndicatorCount': 18},
     {'AreaTypeId': 221, 'IndicatorCount': 18},
     {'AreaTypeId': 15, 'IndicatorCount': 9}]},
   {'Id': 3000010,
    'Name': 'CVD - Risk Factors for CVD',
    'Sequence': 6,
    'ProfileId': 20,
    'DataAvailable': [{'AreaTypeId': 7, 'IndicatorCount': 22},
     {'AreaTypeId': 15, 'IndicatorCount': 22},
     {'AreaTypeId': 66, 'IndicatorCount': 22},
     {'AreaTypeId': 204, 'IndicatorCount': 22},
     {'AreaTypeId': 221, 'IndicatorCount': 22},
     {'AreaTypeId': 15, 'IndicatorCount': 11}]},
   {'Id': 2000002,
    'Name': 'Diabetes',
    'Sequence': 7,
    'ProfileId': 20,
    'DataAvailable': [{'AreaTypeId': 7, 'IndicatorCount': 26},
     {'AreaTypeId': 15, 'IndicatorCount': 26},
     {'AreaTypeId': 66, 'IndicatorCount': 26},
     {'AreaTypeId': 204, 'IndicatorCount': 26},
     {'AreaTypeId': 221, 'IndicatorCount': 26},
     {'AreaTypeId': 15, 'IndicatorCount': 13}]},
   {'Id': 1938133477,
    'Name': 'GP patient survey',
    'Sequence': 8,
    'ProfileId': 20,
    'DataAvailable': [{'AreaTypeId': 7, 'IndicatorCount': 38},
     {'AreaTypeId': 15, 'IndicatorCount': 38},
     {'AreaTypeId': 66, 'IndicatorCount': 38},
     {'AreaTypeId': 204, 'IndicatorCount': 38},
     {'AreaTypeId': 221, 'IndicatorCount': 38},
     {'AreaTypeId': 15, 'IndicatorCount': 19}]},
   {'Id': 2000003,
    'Name': 'Mental Health',
    'Sequence': 9,
    'ProfileId': 20,
    'DataAvailable': [{'AreaTypeId': 7, 'IndicatorCount': 28},
     {'AreaTypeId': 15, 'IndicatorCount': 28},
     {'AreaTypeId': 66, 'IndicatorCount': 28},
     {'AreaTypeId': 204, 'IndicatorCount': 28},
     {'AreaTypeId': 221, 'IndicatorCount': 28},
     {'AreaTypeId': 15, 'IndicatorCount': 14}]},
   {'Id': 2000004,
    'Name': 'QOF prevalences',
    'Sequence': 10,
    'ProfileId': 20,
    'DataAvailable': [{'AreaTypeId': 7, 'IndicatorCount': 46},
     {'AreaTypeId': 15, 'IndicatorCount': 46},
     {'AreaTypeId': 66, 'IndicatorCount': 46},
     {'AreaTypeId': 204, 'IndicatorCount': 46},
     {'AreaTypeId': 221, 'IndicatorCount': 46},
     {'AreaTypeId': 15, 'IndicatorCount': 23}]},
   {'Id': 2000006,
    'Name': 'Respiratory Disease',
    'Sequence': 11,
    'ProfileId': 20,
    'DataAvailable': [{'AreaTypeId': 7, 'IndicatorCount': 24},
     {'AreaTypeId': 15, 'IndicatorCount': 24},
     {'AreaTypeId': 66, 'IndicatorCount': 24},
     {'AreaTypeId': 204, 'IndicatorCount': 24},
     {'AreaTypeId': 221, 'IndicatorCount': 24},
     {'AreaTypeId': 15, 'IndicatorCount': 12}]},
   {'Id': 1938132970,
    'Name': 'AMR Local Indicators',
    'Sequence': 12,
    'ProfileId': 20,
    'DataAvailable': [{'AreaTypeId': 7, 'IndicatorCount': 6},
     {'AreaTypeId': 15, 'IndicatorCount': 6},
     {'AreaTypeId': 66, 'IndicatorCount': 6},
     {'AreaTypeId': 204, 'IndicatorCount': 6},
     {'AreaTypeId': 221, 'IndicatorCount': 6},
     {'AreaTypeId': 15, 'IndicatorCount': 3}]},
   {'Id': 1938133380,
    'Name': 'Vaccinations',
    'Sequence': 13,
    'ProfileId': 20,
    'DataAvailable': [{'AreaTypeId': 7, 'IndicatorCount': 8},
     {'AreaTypeId': 15, 'IndicatorCount': 8},
     {'AreaTypeId': 66, 'IndicatorCount': 8},
     {'AreaTypeId': 204, 'IndicatorCount': 8},
     {'AreaTypeId': 221, 'IndicatorCount': 8},
     {'AreaTypeId': 15, 'IndicatorCount': 4}]}],
  'Visualisations': ['Overview',
   'CompareAreas',
   'Trends',
   'AreaProfile',
   'CompareIndicators',
   'Population',
   'Definitions',
   'BoxPlots',
   'Map',
   'Download'],
  'HasRecentTrends': True,
  'StartValueAxisFromZero': False,
  'IsChangeFromPreviousPeriodShown': False,
  'DefaultAreaTypeId': 7,
  'DefaultTabId': 8,
  'IgnoredSpineChartAreas': None,
  'OpenInequalitiesOnAreaData': False,
  'HasAnyData': True,
  'HasOwnFrontPage': True},
 21: {'Id': 21,
  'Name': 'National General Practice Profiles (supporting indicators)',
  'Key': 'practice-profiles-supporting-indicators',
  'GroupIds': [1200006, 1938133447],
  'GroupMetadata': [{'Id': 1200006,
    'Name': 'National GP Profiles - Supporting Indicators',
    'Sequence': 1,
    'ProfileId': 21,
    'DataAvailable': [{'AreaTypeId': 7, 'IndicatorCount': 10},
     {'AreaTypeId': 15, 'IndicatorCount': 16},
     {'AreaTypeId': 66, 'IndicatorCount': 8},
     {'AreaTypeId': 204, 'IndicatorCount': 10},
     {'AreaTypeId': 221, 'IndicatorCount': 16},
     {'AreaTypeId': 15, 'IndicatorCount': 10}]},
   {'Id': 1938133447,
    'Name': 'Auto update 2',
    'Sequence': 2,
    'ProfileId': 21,
    'DataAvailable': [{'AreaTypeId': 15, 'IndicatorCount': 6},
     {'AreaTypeId': 15, 'IndicatorCount': 3}]}],
  'Visualisations': ['Overview',
   'CompareAreas',
   'Trends',
   'AreaProfile',
   'Definitions',
   'Download'],
  'HasRecentTrends': False,
  'StartValueAxisFromZero': False,
  'IsChangeFromPreviousPeriodShown': False,
  'DefaultAreaTypeId': 15,
  'DefaultTabId': 1,
  'IgnoredSpineChartAreas': ['E06000053', 'E09000001'],
  'OpenInequalitiesOnAreaData': False,
  'HasAnyData': True,
  'HasOwnFrontPage': False},
 26: {'Id': 26,
  'Name': 'Local Authority Health Profiles',
  'Key': 'health-profiles',
  'GroupIds': [1938132696,
   1938132695,
   1938132694,
   8000073,
   1938133217,
   3007000,
   1938133216,
   1938132701,
   1938132974],
  'GroupMetadata': [{'Id': 1938132696,
    'Name': 'Life expectancy and causes of death',
    'Sequence': 1,
    'ProfileId': 26,
    'DataAvailable': [{'AreaTypeId': 6, 'IndicatorCount': 16},
     {'AreaTypeId': 15, 'IndicatorCount': 16},
     {'AreaTypeId': 301, 'IndicatorCount': 16},
     {'AreaTypeId': 302, 'IndicatorCount': 16},
     {'AreaTypeId': 501, 'IndicatorCount': 16},
     {'AreaTypeId': 502, 'IndicatorCount': 16},
     {'AreaTypeId': 15, 'IndicatorCount': 5}]},
   {'Id': 1938132695,
    'Name': 'Injuries and ill health',
    'Sequence': 2,
    'ProfileId': 26,
    'DataAvailable': [{'AreaTypeId': 6, 'IndicatorCount': 12},
     {'AreaTypeId': 15, 'IndicatorCount': 12},
     {'AreaTypeId': 301, 'IndicatorCount': 12},
     {'AreaTypeId': 302, 'IndicatorCount': 12},
     {'AreaTypeId': 501, 'IndicatorCount': 12},
     {'AreaTypeId': 502, 'IndicatorCount': 12},
     {'AreaTypeId': 15, 'IndicatorCount': 6}]},
   {'Id': 1938132694,
    'Name': 'Behavioural risk factors',
    'Sequence': 3,
    'ProfileId': 26,
    'DataAvailable': [{'AreaTypeId': 6, 'IndicatorCount': 10},
     {'AreaTypeId': 15, 'IndicatorCount': 10},
     {'AreaTypeId': 301, 'IndicatorCount': 10},
     {'AreaTypeId': 302, 'IndicatorCount': 10},
     {'AreaTypeId': 501, 'IndicatorCount': 10},
     {'AreaTypeId': 502, 'IndicatorCount': 10},
     {'AreaTypeId': 15, 'IndicatorCount': 5}]},
   {'Id': 8000073,
    'Name': 'Child health',
    'Sequence': 4,
    'ProfileId': 26,
    'DataAvailable': [{'AreaTypeId': 6, 'IndicatorCount': 8},
     {'AreaTypeId': 15, 'IndicatorCount': 8},
     {'AreaTypeId': 301, 'IndicatorCount': 8},
     {'AreaTypeId': 302, 'IndicatorCount': 8},
     {'AreaTypeId': 501, 'IndicatorCount': 8},
     {'AreaTypeId': 502, 'IndicatorCount': 8},
     {'AreaTypeId': 15, 'IndicatorCount': 4}]},
   {'Id': 1938133217,
    'Name': 'Inequalities',
    'Sequence': 5,
    'ProfileId': 26,
    'DataAvailable': [{'AreaTypeId': 6, 'IndicatorCount': 8},
     {'AreaTypeId': 15, 'IndicatorCount': 8},
     {'AreaTypeId': 301, 'IndicatorCount': 8},
     {'AreaTypeId': 302, 'IndicatorCount': 8},
     {'AreaTypeId': 501, 'IndicatorCount': 8},
     {'AreaTypeId': 502, 'IndicatorCount': 8},
     {'AreaTypeId': 15, 'IndicatorCount': 3}]},
   {'Id': 3007000,
    'Name': 'Wider determinants of health',
    'Sequence': 6,
    'ProfileId': 26,
    'DataAvailable': [{'AreaTypeId': 6, 'IndicatorCount': 12},
     {'AreaTypeId': 15, 'IndicatorCount': 12},
     {'AreaTypeId': 301, 'IndicatorCount': 12},
     {'AreaTypeId': 302, 'IndicatorCount': 12},
     {'AreaTypeId': 501, 'IndicatorCount': 12},
     {'AreaTypeId': 502, 'IndicatorCount': 12},
     {'AreaTypeId': 15, 'IndicatorCount': 6}]},
   {'Id': 1938133216,
    'Name': 'Health protection',
    'Sequence': 7,
    'ProfileId': 26,
    'DataAvailable': [{'AreaTypeId': 6, 'IndicatorCount': 6},
     {'AreaTypeId': 15, 'IndicatorCount': 6},
     {'AreaTypeId': 301, 'IndicatorCount': 6},
     {'AreaTypeId': 302, 'IndicatorCount': 6},
     {'AreaTypeId': 501, 'IndicatorCount': 6},
     {'AreaTypeId': 502, 'IndicatorCount': 6},
     {'AreaTypeId': 15, 'IndicatorCount': 3}]},
   {'Id': 1938132701,
    'Name': 'All indicators',
    'Sequence': 8,
    'ProfileId': 26,
    'DataAvailable': [{'AreaTypeId': 6, 'IndicatorCount': 72},
     {'AreaTypeId': 15, 'IndicatorCount': 72},
     {'AreaTypeId': 301, 'IndicatorCount': 72},
     {'AreaTypeId': 302, 'IndicatorCount': 72},
     {'AreaTypeId': 501, 'IndicatorCount': 72},
     {'AreaTypeId': 502, 'IndicatorCount': 72},
     {'AreaTypeId': 15, 'IndicatorCount': 32}]},
   {'Id': 1938132974,
    'Name': 'Supporting information',
    'Sequence': 9,
    'ProfileId': 26,
    'DataAvailable': [{'AreaTypeId': 6, 'IndicatorCount': 8},
     {'AreaTypeId': 15, 'IndicatorCount': 8},
     {'AreaTypeId': 301, 'IndicatorCount': 8},
     {'AreaTypeId': 302, 'IndicatorCount': 8},
     {'AreaTypeId': 501, 'IndicatorCount': 8},
     {'AreaTypeId': 502, 'IndicatorCount': 8},
     {'AreaTypeId': 15, 'IndicatorCount': 4}]}],
  'Visualisations': ['Overview',
   'CompareAreas',
   'Trends',
   'Reports',
   'AreaProfile',
   'CompareIndicators',
   'Population',
   'Definitions',
   'Inequalities',
   'BoxPlots',
   'Map',
   'Download'],
  'HasRecentTrends': True,
  'StartValueAxisFromZero': False,
  'IsChangeFromPreviousPeriodShown': True,
  'DefaultAreaTypeId': 15,
  'DefaultTabId': 1,
  'IgnoredSpineChartAreas': None,
  'OpenInequalitiesOnAreaData': False,
  'HasAnyData': True,
  'HasOwnFrontPage': True},
 29: {'Id': 29,
  'Name': 'Respiratory disease',
  'Key': 'respiratory-disease',
  'GroupIds': [8000003,
   1938133427,
   8000008,
   8000009,
   1938133345,
   8000005,

In [9]:
import pandas as pd

profiles_df = pd.DataFrame([
    {
        "ProfileId": profile["Id"],
        "ProfileName": profile["Name"],
        "ProfileKey": profile["Key"]
    }
    for profile in available_profiles.values()
])

profiles_df.sort_values("ProfileName").reset_index(drop=True)

,ProfileId,ProfileName,ProfileKey
0,101,AMR local indicators - produced by the UKHSA,amr-local-indicators
1,50,Adult mental health and wellbeing,adult-mental-health-wellbeing
2,87,Alcohol Profile,local-alcohol-profiles
3,46,Atlas of Variation,atlas-of-variation
4,92,Cancer Services,cancerservices
5,135,Cardiovascular Disease,cardiovascular
6,161,Cardiovascular Disease Prevention,cardiovascular-disease-prevention
7,147,"Cardiovascular Disease, Diabetes and Kidney Di...",cardiovascular-disease-diabetes-kidney-disease
8,105,Child and Maternal Health,child-health-profiles
9,84,Dementia Profile,dementia
10,156,Development Profile for Testing fingertipsR,development-profile-for-testing-fingertipsr
11,139,Diabetes,diabetes-ft
12,148,Diabetes Footcare,diabetes-footcare
13,137,Fingertips guidance,guidance
14,30,Health Protection,health-protection
15,154,Inequality Tools,inequality-tools
16,58,Learning Disability Profiles,learning-disabilities
17,55,Liver Disease Profiles,liver-disease
18,26,Local Authority Health Profiles,health-profiles
19,143,"Local health, public health data for small geo...",local-health
20,36,Mental Health,mental-health
21,125,Mortality Profile,mortality-profile
22,76,Musculoskeletal health profile,msk
23,65,NHS Health Check,nhs-health-check-detailed
24,20,National General Practice Profiles,general-practice
25,21,National General Practice Profiles (supporting...,practice-profiles-supporting-indicators
26,32,"Obesity, physical activity and nutrition",obesity-physical-activity-nutrition
27,95,Palliative and End of Life Care Profiles,end-of-life
28,159,"Perinatal, children and young people's mental ...",perinatal-cyp-mental-health
29,132,Populations,populations
30,19,Public Health Outcomes Framework,public-health-outcomes-framework
31,29,Respiratory disease,respiratory-disease
32,155,SPOT - Live,spot
33,45,Sexual and Reproductive Health Profiles,sexualhealth
34,18,Smoking Profile,tobacco-control
35,91,Suicide Prevention,suicide-prevention
36,86,TB Strategy Monitoring Indicators,tb-monitoring
37,165,Vision,vision
38,130,Wider Determinants of Health,wider-determinants

In [10]:
help(ftp.get_all_profiles)

Help on function get_all_profiles in module fingertips_py.metadata:

get_all_profiles(is_test=False)
    Returns all profiles.

    :param is_test: Used for testing. Returns a tuple of expected return and the URL called to retrieve the data
    :return: A dictionary of all profiles in Fingertips including information on domains and sequencing

Public Health Outcomes Framework selected because it contains indicators related to healthcare activity, hospital usage, and outcomes.

In [11]:
profiles_df[profiles_df["ProfileName"].str.contains("outcomes", case=False)]

,ProfileId,ProfileName,ProfileKey
1,19,Public Health Outcomes Framework,public-health-outcomes-framework

In [13]:
phof_profile = ftp.get_profile_by_name("public health outcomes framework")
phof_profile

{'Id': 19,
 'Name': 'Public Health Outcomes Framework',
 'Key': 'public-health-outcomes-framework',
 'GroupIds': [1000049, 1000041, 1000042, 1000043, 1000044, 1938132983],
 'GroupMetadata': [{'Id': 1000049,
   'Name': 'A. Overarching indicators',
   'Sequence': 1,
   'ProfileId': 19,
   'DataAvailable': [{'AreaTypeId': 6, 'IndicatorCount': 40},
    {'AreaTypeId': 15, 'IndicatorCount': 44},
    {'AreaTypeId': 221, 'IndicatorCount': 8},
    {'AreaTypeId': 223, 'IndicatorCount': 8},
    {'AreaTypeId': 301, 'IndicatorCount': 24},
    {'AreaTypeId': 302, 'IndicatorCount': 38},
    {'AreaTypeId': 501, 'IndicatorCount': 24},
    {'AreaTypeId': 502, 'IndicatorCount': 44},
    {'AreaTypeId': 15, 'IndicatorCount': 10}]},
  {'Id': 1000041,
   'Name': 'B. Wider determinants of health',
   'Sequence': 2,
   'ProfileId': 19,
   'DataAvailable': [{'AreaTypeId': 6, 'IndicatorCount': 72},
    {'AreaTypeId': 15, 'IndicatorCount': 72},
    {'AreaTypeId': 221, 'IndicatorCount': 32},
    {'AreaTypeId': 223, 'IndicatorCount': 32},
    {'AreaTypeId': 301, 'IndicatorCount': 36},
    {'AreaTypeId': 302, 'IndicatorCount': 72},
    {'AreaTypeId': 501, 'IndicatorCount': 36},
    {'AreaTypeId': 502, 'IndicatorCount': 72},
    {'AreaTypeId': 15, 'IndicatorCount': 36}]},
  {'Id': 1000042,
   'Name': 'C. Health improvement',
   'Sequence': 3,
   'ProfileId': 19,
   'DataAvailable': [{'AreaTypeId': 6, 'IndicatorCount': 130},
    {'AreaTypeId': 15, 'IndicatorCount': 130},
    {'AreaTypeId': 221, 'IndicatorCount': 62},
    {'AreaTypeId': 223, 'IndicatorCount': 50},
    {'AreaTypeId': 301, 'IndicatorCount': 72},
    {'AreaTypeId': 302, 'IndicatorCount': 110},
    {'AreaTypeId': 501, 'IndicatorCount': 72},
    {'AreaTypeId': 502, 'IndicatorCount': 110},
    {'AreaTypeId': 15, 'IndicatorCount': 63}]},
  {'Id': 1000043,
   'Name': 'D. Health protection',
   'Sequence': 4,
   'ProfileId': 19,
   'DataAvailable': [{'AreaTypeId': 6, 'IndicatorCount': 72},
    {'AreaTypeId': 15, 'IndicatorCount': 72},
    {'AreaTypeId': 221, 'IndicatorCount': 64},
    {'AreaTypeId': 223, 'IndicatorCount': 26},
    {'AreaTypeId': 301, 'IndicatorCount': 18},
    {'AreaTypeId': 302, 'IndicatorCount': 72},
    {'AreaTypeId': 501, 'IndicatorCount': 18},
    {'AreaTypeId': 502, 'IndicatorCount': 72},
    {'AreaTypeId': 15, 'IndicatorCount': 33}]},
  {'Id': 1000044,
   'Name': 'E. Healthcare and premature mortality',
   'Sequence': 5,
   'ProfileId': 19,
   'DataAvailable': [{'AreaTypeId': 6, 'IndicatorCount': 70},
    {'AreaTypeId': 15, 'IndicatorCount': 72},
    {'AreaTypeId': 221, 'IndicatorCount': 60},
    {'AreaTypeId': 223, 'IndicatorCount': 60},
    {'AreaTypeId': 301, 'IndicatorCount': 50},
    {'AreaTypeId': 302, 'IndicatorCount': 62},
    {'AreaTypeId': 501, 'IndicatorCount': 50},
    {'AreaTypeId': 502, 'IndicatorCount': 62},
    {'AreaTypeId': 15, 'IndicatorCount': 26}]},
  {'Id': 1938132983,
   'Name': 'Supporting information',
   'Sequence': 6,
   'ProfileId': 19,
   'DataAvailable': [{'AreaTypeId': 6, 'IndicatorCount': 10},
    {'AreaTypeId': 15, 'IndicatorCount': 10},
    {'AreaTypeId': 221, 'IndicatorCount': 6},
    {'AreaTypeId': 223, 'IndicatorCount': 6},
    {'AreaTypeId': 301, 'IndicatorCount': 10},
    {'AreaTypeId': 302, 'IndicatorCount': 10},
    {'AreaTypeId': 501, 'IndicatorCount': 10},
    {'AreaTypeId': 502, 'IndicatorCount': 10},
    {'AreaTypeId': 15, 'IndicatorCount': 5}]}],
 'Visualisations': ['Overview',
  'CompareAreas',
  'Trends',
  'Reports',
  'AreaProfile',
  'CompareIndicators',
  'Population',
  'Definitions',
  'Inequalities',
  'BoxPlots',
  'Map',
  'Download'],
 'HasRecentTrends': True,
 'StartValueAxisFromZero': True,
 'IsChangeFromPreviousPeriodShown': True,
 'DefaultAreaTypeId': 502,
 'DefaultTabId': 3,
 'IgnoredSpineChartAreas': ['E06000053', 'E09000001'],
 'OpenInequalitiesOnAreaData': False,
 'HasAnyData': True,
 'HasOwnFrontPage': True}

In [14]:
# Pull all indicator metadata for the PHOF profile
phof_indicators_df = ftp.get_metadata_for_profile_as_dataframe(phof_profile["Id"])

# Preview structure
phof_indicators_df.head()

,Indicator ID,Indicator,Indicator number,Rationale,Specific rationale,Definition,Data source,Indicator source,Definition of numerator,Source of numerator,...,Data re-use,Links,Indicator Content,Simple Name,Simple Definition,Unit,Value type,Year type,Polarity,Date updated
0,90362,A01a - Healthy life expectancy at birth,A01a,This indicator is an extremely important summa...,NaN,A measure of the average number of years a per...,Office for National Statistics,"<span style=""line-height: 115%; mso-ascii-them...",Number of deaths registered in the respective ...,"Office for National Statistics (ONS), Annual b...",...,You may use and re use Crown copyright informa...,Guides to the methods used in calculation of t...,NaN,Healthy life expectancy at birth,The average number of years a person would exp...,Years,Life expectancy,Calendar,RAG - High is good,21/07/2025
1,90366,A01b - Life expectancy at birth,A01b,This indicator gives context to healthy life e...,NaN,The average number of years a person would exp...,Office for National Statistics,https://www.ons.gov.uk/peoplepopulationandcomm...,Number of deaths registered in the respective ...,"Office for National Statistics (ONS), Annual m...",...,You may use and re use Crown copyright informa...,Life expectancy at birth: methodological optio...,NaN,Life expectancy at birth,The average number of years a person would exp...,Years,Life expectancy,Calendar,RAG - High is good,23/04/2025
2,91102,A01b - Life expectancy at 65,A01b,This indicator gives context to healthy life e...,NaN,The average number of years a person would exp...,Office for National Statistics,https://www.ons.gov.uk/peoplepopulationandcomm...,Number of deaths registered in the respective ...,"Office for National Statistics (ONS), Annual m...",...,You may use and re use Crown copyright informa...,Life expectancy: methodological options for sm...,NaN,NaN,NaN,Years,Life expectancy,Calendar,RAG - High is good,23/04/2025
3,93562,A01c - Disability free life expectancy at birth,A01c,This indicator will provide more information o...,NaN,A measure of the average number of years a per...,Office for National Statistics,"<p class=""MsoNormal"">Office for National Stati...",NaN,"Office for National Statistics (ONS), Annual b...",...,You may use and re use Crown copyright informa...,"<p class=""MsoNormal"">Guides to the methods use...",NaN,NaN,NaN,Years,Life expectancy,Calendar,RAG - High is good,05/04/2022
4,92901,A02a - Inequality in life expectancy at birth,A02a,This is a key high level health inequalities o...,NaN,This indicator measures inequalities in life e...,"OHID, based on Ministry of Housing, Communitie...",NaN,NaN,"Office for National Statistics (ONS), Annual m...",...,You may use and re use Crown copyright informa...,"<p class=""MsoNormal"">Guides to the methods use...",NaN,Inequality in life expectancy at birth,The difference between the most and least depr...,Years,Slope Index of Inequality,Calendar,RAG - Low is good,23/04/2025

In [15]:
phof_indicators_df.columns

Index(['Indicator ID', 'Indicator', 'Indicator number', 'Rationale',
       'Specific rationale', 'Definition', 'Data source', 'Indicator source',
       'Definition of numerator', 'Source of numerator',
       'Definition of denominator', 'Source of denominator', 'Methodology',
       'Standard population/values', 'Frequency',
       'Confidence interval details', 'Disclosure control', 'Rounding',
       'Caveats', 'Notes', 'Impact of COVID-19', 'Copyright', 'Data re-use',
       'Links', 'Indicator Content', 'Simple Name', 'Simple Definition',
       'Unit', 'Value type', 'Year type', 'Polarity', 'Date updated'],
      dtype='object')

In [16]:
admissions_candidates_df = phof_indicators_df[
    phof_indicators_df["Indicator"].str.contains(
        "admission|emergency|hospital|avoidable|preventable",
        case=False,
        na=False
    )
]

admissions_candidates_df[["Indicator ID", "Indicator"]].sort_values("Indicator").head(25)

     Indicator ID                                          Indicator
20          11201  B12a - Violent crime - hospital admissions for...
58          90284  C11a - Hospital admissions caused by unintenti...
60          90832  C11a - Hospital admissions caused by unintenti...
61          90285  C11b - Hospital admissions caused by unintenti...
63          21001  C14b - Emergency Hospital Admissions for Inten...
78          93764  C21 - Admission episodes for alcohol-related c...
84          22401  C29 - Emergency hospital admissions due to fal...
87          22402  C29 - Emergency hospital admissions due to fal...
88          22403  C29 - Emergency hospital admissions due to fal...
144         93721  E03 - Under 75 mortality rate from causes cons...
146         93722  E04b - Under 75 mortality rate from cardiovasc...
148         93723  E05b - Under 75 mortality rate from cancer con...
150         93720  E06b - Under 75 mortality rate from liver dise...
152         93724  E07b - Under 75 mortality rate from respirator...
156         41101  E11 - Emergency readmissions within 30 days of...
160         41201  E12a - Preventable sight loss: age related mac...
162         41202            E12b - Preventable sight loss: glaucoma
164         41203  E12c - Preventable sight loss: diabetic eye di...
166         41204  E12d - Preventable sight loss: sight loss cert...

This indicator helps explain healthcare cost differences by showing who uses emergency care more frequently.

In [17]:
# Set chosen indicator
ADMISSIONS_INDICATOR_ID = 21001

# Pull data using API
admissions_raw_df = ftp.get_data_for_indicator_at_all_available_geographies(ADMISSIONS_INDICATOR_ID)

# Preview data
admissions_raw_df.head()

C:\Users\HeatherMoorhouse\AppData\Local\Programs\Python\Python314\Lib\site-packages\fingertips_py\retrieve_data.py:164: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, df_temp])

,Indicator ID,Indicator Name,Parent Code,Parent Name,Area Code,Area Name,Area Type,Sex,Age,Category Type,...,Count,Denominator,Value note,Recent Trend,Compared to England value or percentiles,Compared to percentiles,Time period Sortable,New data,Compared to goal,Time period range
0,21001,Emergency Hospital Admissions for Intentional ...,NaN,NaN,E92000001,England,England,Male,All ages,NaN,...,43319.0,25877244.0,NaN,NaN,Not compared,Not compared,20100000,NaN,NaN,1y
1,21001,Emergency Hospital Admissions for Intentional ...,NaN,NaN,E92000001,England,England,Female,All ages,NaN,...,65372.0,26765208.0,NaN,NaN,Not compared,Not compared,20100000,NaN,NaN,1y
2,21001,Emergency Hospital Admissions for Intentional ...,NaN,NaN,E92000001,England,England,Persons,All ages,NaN,...,108694.0,52642452.0,NaN,NaN,Not compared,Not compared,20100000,NaN,NaN,1y
3,21001,Emergency Hospital Admissions for Intentional ...,E92000001,England,E92000001,England,England,Male,All ages,NaN,...,43319.0,25877244.0,NaN,NaN,Similar,Not compared,20100000,NaN,NaN,1y
4,21001,Emergency Hospital Admissions for Intentional ...,E92000001,England,E92000001,England,England,Female,All ages,NaN,...,65372.0,26765208.0,NaN,NaN,Similar,Not compared,20100000,NaN,NaN,1y

### Clean Data Set

In [18]:
admissions_raw_df[['Time period', 'Time period Sortable', 'Time period range']].head(10)

  Time period Time period Sortable Time period range
0     2010/11             20100000                1y
1     2010/11             20100000                1y
2     2010/11             20100000                1y
3     2010/11             20100000                1y
4     2010/11             20100000                1y
5     2010/11             20100000                1y
6     2010/11             20100000                1y
7     2010/11             20100000                1y
8     2010/11             20100000                1y
9     2010/11             20100000                1y

In [19]:
# Select analysis columns
admissions_clean_df = admissions_raw_df[
    ['Time period Sortable', 'Sex', 'Area Name', 'Value']
].copy()

# Rename columns
admissions_clean_df.columns = ['Year', 'Sex', 'Area', 'Value']

# Convert sortable year into numeric year
admissions_clean_df['Year'] = admissions_clean_df['Year'].astype(int) // 10000

# Ensure Value is numeric
admissions_clean_df['Value'] = pd.to_numeric(admissions_clean_df['Value'], errors='coerce')

# Filter to male vs female only
admissions_clean_df = admissions_clean_df[admissions_clean_df['Sex'].isin(['Male', 'Female'])]

# Preview clean data
admissions_clean_df.head()

   Year     Sex        Area       Value
0  2010    Male     England  160.411961
1  2010  Female     England  235.857736
3  2010    Male     England  160.411961
4  2010  Female     England  235.857736
6  2010    Male  Hartlepool  352.142738

Fingertips displays time as a formatted label (e.g. "2010/11") and a numeric sortable value. We used the sortable time field to safely extract numerical years for trend analysis.

In [20]:
admissions_clean_df['Year'].unique()[:6]

array([2010, 2011, 2012, 2013, 2014, 2015])

In [21]:
# Remove duplicate England entries
admissions_final_df = admissions_clean_df.drop_duplicates(
    subset=['Year', 'Sex', 'Area']
)

admissions_final_df.head()

   Year     Sex                  Area       Value
0  2010    Male               England  160.411961
1  2010  Female               England  235.857736
6  2010    Male            Hartlepool  352.142738
7  2010    Male         Middlesbrough  458.955084
8  2010    Male  Redcar and Cleveland  328.612959

In [22]:
# storing the final dataframe for visualisations

%store admissions_final_df

Stored 'admissions_final_df' (DataFrame)