Installing libraries and importing modules

In [7]:
import pandas as pd

file_path = "../data/raw/Integrated-Patient-Level-Activity-and-Costing-2021-22.csv"
df = pd.read_csv(file_path)

df.head()

,YEAR,DATA_SET,ORG_LEVEL,ORG_CODE,ORG_NAME,BREAKDOWN,BREAKDOWN_GROUP_1,BREAKDOWN_GROUP_2,ACTIVITY_COUNT,TOTAL_COST
0,202122,APC,ALL,ALL,ALL SUBMITTERS,Diagnosis,Diseases of the skin and subcutaneous tissue,NaN,363861.000000,6.102477e+08
1,202122,APC,ALL,ALL,ALL SUBMITTERS,Diagnosis,"Endocrine, nutritional and metabolic diseases",NaN,427412.000000,7.211952e+08
2,202122,IAPT,ALL,ALL,ALL SUBMITTERS,Cluster Assessment Status and Cluster,Patient assessed and assigned an Adult Mental ...,06 - Non-Psychotic Disorder of Over-Valued Ideas,9938.000000,1.731191e+06
3,202122,IAPT,ALL,ALL,ALL SUBMITTERS,Cluster Assessment Status and Cluster,Patient assessed and assigned an Adult Mental ...,07 - Enduring Non-Psychotic Disorders (High Di...,12747.000000,2.147146e+06
4,202122,IAPT,ALL,ALL,ALL SUBMITTERS,Cluster Assessment Status and Cluster,Patient assessed and assigned an Adult Mental ...,08 - Non-Psychotic Chaotic and Challenging Dis...,2871.000000,4.320896e+05

In [8]:
#Here I'm selecting which columns to include and dropping the remainder irrelevant ones
df["BREAKDOWN_GROUP_1"] = df["BREAKDOWN_GROUP_1"].astype(str).str.strip()
df["BREAKDOWN_GROUP_2"] = df["BREAKDOWN_GROUP_2"].astype(str).str.strip()

df["ACTIVITY_COUNT"] = pd.to_numeric(df["ACTIVITY_COUNT"], errors="coerce")
df["TOTAL_COST"] = pd.to_numeric(df["TOTAL_COST"], errors="coerce")


df = df.dropna(subset=["ACTIVITY_COUNT", "TOTAL_COST"], how="all")

df.head()

,YEAR,DATA_SET,ORG_LEVEL,ORG_CODE,ORG_NAME,BREAKDOWN,BREAKDOWN_GROUP_1,BREAKDOWN_GROUP_2,ACTIVITY_COUNT,TOTAL_COST
0,202122,APC,ALL,ALL,ALL SUBMITTERS,Diagnosis,Diseases of the skin and subcutaneous tissue,nan,363861.0,6.102477e+08
1,202122,APC,ALL,ALL,ALL SUBMITTERS,Diagnosis,"Endocrine, nutritional and metabolic diseases",nan,427412.0,7.211952e+08
2,202122,IAPT,ALL,ALL,ALL SUBMITTERS,Cluster Assessment Status and Cluster,Patient assessed and assigned an Adult Mental ...,06 - Non-Psychotic Disorder of Over-Valued Ideas,9938.0,1.731191e+06
3,202122,IAPT,ALL,ALL,ALL SUBMITTERS,Cluster Assessment Status and Cluster,Patient assessed and assigned an Adult Mental ...,07 - Enduring Non-Psychotic Disorders (High Di...,12747.0,2.147146e+06
4,202122,IAPT,ALL,ALL,ALL SUBMITTERS,Cluster Assessment Status and Cluster,Patient assessed and assigned an Adult Mental ...,08 - Non-Psychotic Chaotic and Challenging Dis...,2871.0,4.320896e+05

In [9]:

# filter to male and female only
gender_df = df[df["BREAKDOWN_GROUP_1"].isin(["Male", "Female"])].copy()

# keeps only the required columns
gender_df = gender_df[[
    "BREAKDOWN",
    "BREAKDOWN_GROUP_1",
    "BREAKDOWN_GROUP_2",
    "ACTIVITY_COUNT",
    "TOTAL_COST"
]].copy()

#reformat ACTIVITY_COUNT and TOTAL_COST
gender_df["ACTIVITY_COUNT"] = (
    gender_df["ACTIVITY_COUNT"]
    .fillna(0)
    .round(0)
    .astype(int)
    .map("{:,}".format)
)

gender_df["TOTAL_COST"] = (
    gender_df["TOTAL_COST"]
    .fillna(0)
    .round(0)
    .astype(int)
    .map("£{:,.0f}".format)
)


gender_df.head(20)

,BREAKDOWN,BREAKDOWN_GROUP_1,BREAKDOWN_GROUP_2,ACTIVITY_COUNT,TOTAL_COST
6,Sex and Age Group,Female,80-84 years,"642,609","£1,609,173,362"
7,Sex and Age Group,Female,85-89 years,"538,576","£1,457,331,396"
8,Sex and Age Group,Female,90-94 years,"307,462","£887,009,480"
37,Sex and Age Group,Female,0 years,"208,352","£35,405,523"
38,Sex and Age Group,Female,01-04 years,"536,027","£91,711,675"
39,Sex and Age Group,Male,30-34 years,"218,303","£383,703,947"
40,Sex and Age Group,Male,35-39 years,"239,127","£436,654,049"
41,Sex and Age Group,Male,40-44 years,"264,984","£485,662,707"
42,Sex and Age Group,Male,45-49 years,"307,961","£567,549,934"
53,Sex and Age Group,Female,50-54 years,"2,713,691","£470,693,787"
54,Sex and Age Group,Female,55-59 years,"2,970,962","£509,017,567"
67,Sex and Age Group,Male,80-84 years,"290,201","£106,486,014"
68,Sex and Age Group,Male,85-89 years,"221,599","£85,315,383"
69,Sex and Age Group,Male,90-94 years,"105,183","£42,499,517"
90,Sex and Age Group,Female,01-04 years,"159,952","£292,703,877"
91,Sex and Age Group,Female,05-09 years,"103,938","£210,029,939"
92,Sex and Age Group,Female,10-14 years,"115,019","£293,452,282"
104,Sex and Age Group,Female,05-09 years,"325,128","£55,663,064"
105,Sex and Age Group,Female,10-14 years,"373,231","£67,343,322"
106,Sex and Age Group,Female,15-19 years,"478,074","£97,984,032"

In [10]:
#Format numbers nicely

summary_reformatted = gender_summary.copy()

summary_reformatted["ACTIVITY_COUNT"] = (
    summary_reformatted["ACTIVITY_COUNT"]
    .round(0)
    .astype(int)
    .map("{:,}".format)
)

summary_reformatted["TOTAL_COST"] = (
    summary_reformatted["TOTAL_COST"]
    .round(0)
    .astype(int)
    .map("£{:,.0f}".format)
)

summary_reformatted

NameError: name 'gender_summary' is not defined